name: QMake Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:
        version: 5.15.2
        target: desktop
    - name: Configure QMake
      working-directory: ${{github.workspace}}
      run: qmake fortune-avenue-port.pro

    - name: Build
      working-directory: ${{github.workspace}}
      run: make

    - name: Deploy
      working-directory: ${{github.workspace}}
      run: macdeployqt 'Fortune Avenue.app' -dmg

    - name: Rename
      working-directory: ${{github.workspace}}
      run: mv 'Fortune Avenue.dmg' 'fortune-avenue.dmg'
      
