name: QMake Build

on:
  release:
    types: [published]
  push:
    branches:
      - 'release/**'

env:
  BUILD_TYPE: Release
  VERSION_NAME: ${{ github.event.release.tag_name }}

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:
        version: 5.15.2
        target: desktop

    - name: Configure QMake
      working-directory: ${{github.workspace}}
      run: qmake fortune-avenue-port.pro -config release

    - name: Build
      working-directory: ${{github.workspace}}
      run: make

    - name: Deploy
      working-directory: ${{github.workspace}}
      run: macdeployqt 'Fortune Avenue.app' -dmg

    - name: Rename
      working-directory: ${{github.workspace}}
      run: mv 'Fortune Avenue.dmg' "fortune-avenue-$VERSION_NAME-macos.dmg"

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{github.workspace}}/fortune-avenue-${{github.event.release.tag_name}}-macos.dmg
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:
        version: 5.15.2
        target: desktop
        arch: win64_mingw81

    - name: Configure QMake
      working-directory: ${{github.workspace}}
      run: qmake fortune-avenue-port.pro

    - name: Build
      working-directory: ${{github.workspace}}
      run: mingw32-make

    - name: Rename
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        mkdir "fortune-avenue-$VERSION_NAME"
        mv "release/Fortune Avenue.exe" "fortune-avenue-$VERSION_NAME/Fortune Avenue.exe"

    - name: Deploy
      working-directory: ${{github.workspace}}
      shell: bash
      run: windeployqt "fortune-avenue-$VERSION_NAME/Fortune Avenue.exe"

    - name: Archive
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: ${{github.workspace}}
        filename: fortune-avenue-${{github.event.release.tag_name}}-windows.zip
        path: ./fortune-avenue-${{github.event.release.tag_name}}/

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{github.workspace}}/fortune-avenue-${{github.event.release.tag_name}}-windows.zip

